export const FILE_LIST_DATA = 'FILE_LIST_DATA';
export const UPDATE_FILE_LIST_DATA = 'UPDATE_FILE_LIST_DATA';
export const DATA_SET_SELECTED = 'DATA_SET_SELECTED';
export const SECTION_SELECTED = 'SECTION_SELECTED';